# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Semantic Release"

on:
  push:
    branches:
      - ([0-9])?(.{+([0-9]),x}).x
      - master
      - next
      - next-major
      - alpha
      - beta

jobs:
  text-lint:
    name: "Semantic Release"

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: "Setup node"
        uses: actions/setup-node@v1
        with:
          node-version: "12.16.3"

      - name: "Cache dependencies"
        uses: actions/cache@v1
        with:
          key: npm-${{ hashFiles('package-lock.json') }}
          path: ~/.npm
          restore-keys: |
            npm-

      - name: "Install dependencies"
        run: npm ci --ignore-scripts --no-audit --no-progress --prefer-offline

      - name: "Release"
        if: ${{ github.repository != 'narrowspark/php-library-template' }}
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
